# Generated by Django 5.2 on 2025-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('mode', models.CharField(choices=[('words', 'Words'), ('time', 'Time')], max_length=10)),
                ('time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('words_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
