# Generated by Django 5.2 on 2025-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0003_team_result_session_id_result_user_teammembership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='result',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='result',
            name='played_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
