# Generated by Django 5.2 on 2025-05-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0004_remove_teammembership_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='words_count',
            new_name='word_count',
        ),
    ]
