# Generated by Django 5.2 on 2025-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0006_alter_result_user_delete_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time_seconds',
        ),
        migrations.RemoveField(
            model_name='result',
            name='time',
        ),
        migrations.AddField(
            model_name='result',
            name='time_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='wpm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
