# Generated by Django 5.2 on 2025-05-16 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0004_teammessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammessage',
            old_name='message',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.team'),
        ),
    ]
