# Generated by Django 5.2 on 2025-05-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='words_count',
        ),
    ]
