# Generated by Django 5.2 on 2025-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='game',
        ),
        migrations.AddField(
            model_name='competition',
            name='phrase',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
