# Generated by Django 5.2 on 2025-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_remove_competition_game_competition_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
