# Generated by Django 5.2 on 2025-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_competition_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='tries_left',
        ),
        migrations.AddField(
            model_name='competition',
            name='max_tries',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='tries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
