# Generated by Django 5.2 on 2025-05-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_remove_competitionparticipant_tries_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='is_active',
        ),
    ]
