# Generated by Django 5.2 on 2025-05-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_alter_competitionparticipant_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='tries',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
