# Generated by Django 5.2 on 2025-05-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_alter_competitionparticipant_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionparticipant',
            name='ack',
            field=models.BooleanField(default=False),
        ),
    ]
