# Generated by Django 5.2 on 2025-05-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_competitionparticipant_ack'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
