# Generated by Django 5.2 on 2025-05-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='satus',
            new_name='status',
        ),
    ]
